//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MGuzmanPinturasEntities : DbContext
    {
        public MGuzmanPinturasEntities()
            : base("name=MGuzmanPinturasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Pintura> Pinturas { get; set; }
    
        public virtual int PinturaAdd(string color, Nullable<System.DateTime> fechaDeProduccion, Nullable<System.DateTime> fechaDeCaducacion)
        {
            var colorParameter = color != null ?
                new ObjectParameter("Color", color) :
                new ObjectParameter("Color", typeof(string));
    
            var fechaDeProduccionParameter = fechaDeProduccion.HasValue ?
                new ObjectParameter("FechaDeProduccion", fechaDeProduccion) :
                new ObjectParameter("FechaDeProduccion", typeof(System.DateTime));
    
            var fechaDeCaducacionParameter = fechaDeCaducacion.HasValue ?
                new ObjectParameter("FechaDeCaducacion", fechaDeCaducacion) :
                new ObjectParameter("FechaDeCaducacion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PinturaAdd", colorParameter, fechaDeProduccionParameter, fechaDeCaducacionParameter);
        }
    
        public virtual int PinturaDelete(Nullable<int> idPintura)
        {
            var idPinturaParameter = idPintura.HasValue ?
                new ObjectParameter("IdPintura", idPintura) :
                new ObjectParameter("IdPintura", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PinturaDelete", idPinturaParameter);
        }
    
        public virtual ObjectResult<PinturaGetAll_Result> PinturaGetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PinturaGetAll_Result>("PinturaGetAll");
        }
    
        public virtual ObjectResult<PinturaGetById_Result> PinturaGetById(Nullable<int> idPintura)
        {
            var idPinturaParameter = idPintura.HasValue ?
                new ObjectParameter("IdPintura", idPintura) :
                new ObjectParameter("IdPintura", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PinturaGetById_Result>("PinturaGetById", idPinturaParameter);
        }
    }
}
