//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pintura
    {
        public int IdPintura { get; set; }
        public string Color { get; set; }
        public Nullable<System.DateTime> FechaDeProduccion { get; set; }
        public Nullable<System.DateTime> FechaDeCaducacion { get; set; }
    }
}
